name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Build
        run: flutter build web --web-renderer canvaskit

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      - name: Move to Publish Repository
        if: github.ref == 'refs/heads/main' && success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add destination_repo https://github.com/aerodk/aerodk.github.io.git        
          git clone https://github.com/aerodk/aerodk.github.io.git tmp-repo
          cd tmp-repo
          git switch -c "release-dotmein-$(date +'%Y%m%d%H%M%S')"
          cp -r ../build/web/* DotMeIn/
          git add --all .
          git commit -m "Release @ $(date +'%Y%m%d%H%M%S')_${{ github.run_number }}"
          git push --set-upstream origin "release-dotmein-${{ github.sha }}" 
